"""Specimens

Revision ID: 6ede5d9b2133
Revises: 
Create Date: 2025-03-27 15:56:33.261060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ede5d9b2133'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bacterial_species',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('last_update_date', sa.DateTime(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('last_update_by', sa.String(length=200), nullable=False),
    sa.Column('created_by', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bacterial_species_name'), 'bacterial_species', ['name'], unique=True)
    op.create_table('box_number',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('last_update_date', sa.DateTime(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('last_update_by', sa.String(length=200), nullable=False),
    sa.Column('created_by', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_box_number_name'), 'box_number', ['name'], unique=True)
    op.create_table('medium',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('last_update_date', sa.DateTime(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('last_update_by', sa.String(length=200), nullable=False),
    sa.Column('created_by', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medium_name'), 'medium', ['name'], unique=True)
    op.create_table('phage_identifier',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('last_update_date', sa.DateTime(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('last_update_by', sa.String(length=200), nullable=False),
    sa.Column('created_by', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_phage_identifier_name'), 'phage_identifier', ['name'], unique=True)
    op.create_table('plasmid',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('last_update_date', sa.DateTime(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('last_update_by', sa.String(length=200), nullable=False),
    sa.Column('created_by', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plasmid_name'), 'plasmid', ['name'], unique=True)
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('last_update_date', sa.DateTime(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('last_update_by', sa.String(length=200), nullable=False),
    sa.Column('created_by', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_name'), 'project', ['name'], unique=True)
    op.create_table('resistance_marker',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('last_update_date', sa.DateTime(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('last_update_by', sa.String(length=200), nullable=False),
    sa.Column('created_by', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resistance_marker_name'), 'resistance_marker', ['name'], unique=True)
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('staff_member',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('last_update_date', sa.DateTime(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('last_update_by', sa.String(length=200), nullable=False),
    sa.Column('created_by', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_staff_member_name'), 'staff_member', ['name'], unique=True)
    op.create_table('storage_method',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('last_update_date', sa.DateTime(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('last_update_by', sa.String(length=200), nullable=False),
    sa.Column('created_by', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_storage_method_name'), 'storage_method', ['name'], unique=True)
    op.create_table('strain',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('last_update_date', sa.DateTime(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('last_update_by', sa.String(length=200), nullable=False),
    sa.Column('created_by', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_strain_name'), 'strain', ['name'], unique=True)
    op.create_table('upload',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('errors', sa.Text(), nullable=False),
    sa.Column('last_update_date', sa.DateTime(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('last_update_by', sa.String(length=200), nullable=False),
    sa.Column('created_by', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('current_login_at', sa.DateTime(), nullable=True),
    sa.Column('last_login_ip', sa.String(length=50), nullable=True),
    sa.Column('current_login_ip', sa.String(length=50), nullable=True),
    sa.Column('login_count', sa.Integer(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('ldap_user', sa.Boolean(), nullable=True),
    sa.Column('fs_uniquifier', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('fs_uniquifier'),
    sa.UniqueConstraint('username')
    )
    op.create_table('roles_users',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.create_table('specimen',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('freezer', sa.Integer(), nullable=False),
    sa.Column('drawer', sa.Integer(), nullable=False),
    sa.Column('position', sa.String(length=20), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('sample_date', sa.Date(), nullable=False),
    sa.Column('box_number_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('storage_method_id', sa.Integer(), nullable=True),
    sa.Column('staff_member_id', sa.Integer(), nullable=True),
    sa.Column('last_update_date', sa.DateTime(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('last_update_by', sa.String(length=200), nullable=False),
    sa.Column('created_by', sa.String(length=200), nullable=False),
    sa.Column('species_id', sa.Integer(), nullable=True),
    sa.Column('strain_id', sa.Integer(), nullable=True),
    sa.Column('medium_id', sa.Integer(), nullable=True),
    sa.Column('plasmid_id', sa.Integer(), nullable=True),
    sa.Column('resistance_marker_id', sa.Integer(), nullable=True),
    sa.Column('phage_identifier_id', sa.Integer(), nullable=True),
    sa.Column('host_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['box_number_id'], ['box_number.id'], ),
    sa.ForeignKeyConstraint(['host_id'], ['bacterial_species.id'], ),
    sa.ForeignKeyConstraint(['medium_id'], ['medium.id'], ),
    sa.ForeignKeyConstraint(['phage_identifier_id'], ['phage_identifier.id'], ),
    sa.ForeignKeyConstraint(['plasmid_id'], ['plasmid.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['resistance_marker_id'], ['resistance_marker.id'], ),
    sa.ForeignKeyConstraint(['species_id'], ['bacterial_species.id'], ),
    sa.ForeignKeyConstraint(['staff_member_id'], ['staff_member.id'], ),
    sa.ForeignKeyConstraint(['storage_method_id'], ['storage_method.id'], ),
    sa.ForeignKeyConstraint(['strain_id'], ['strain.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_specimen_box_number_id'), 'specimen', ['box_number_id'], unique=False)
    op.create_index(op.f('ix_specimen_description'), 'specimen', ['description'], unique=False)
    op.create_index(op.f('ix_specimen_drawer'), 'specimen', ['drawer'], unique=False)
    op.create_index(op.f('ix_specimen_freezer'), 'specimen', ['freezer'], unique=False)
    op.create_index(op.f('ix_specimen_host_id'), 'specimen', ['host_id'], unique=False)
    op.create_index(op.f('ix_specimen_medium_id'), 'specimen', ['medium_id'], unique=False)
    op.create_index(op.f('ix_specimen_name'), 'specimen', ['name'], unique=False)
    op.create_index(op.f('ix_specimen_notes'), 'specimen', ['notes'], unique=False)
    op.create_index(op.f('ix_specimen_phage_identifier_id'), 'specimen', ['phage_identifier_id'], unique=False)
    op.create_index(op.f('ix_specimen_plasmid_id'), 'specimen', ['plasmid_id'], unique=False)
    op.create_index(op.f('ix_specimen_position'), 'specimen', ['position'], unique=False)
    op.create_index(op.f('ix_specimen_project_id'), 'specimen', ['project_id'], unique=False)
    op.create_index(op.f('ix_specimen_resistance_marker_id'), 'specimen', ['resistance_marker_id'], unique=False)
    op.create_index(op.f('ix_specimen_sample_date'), 'specimen', ['sample_date'], unique=False)
    op.create_index(op.f('ix_specimen_species_id'), 'specimen', ['species_id'], unique=False)
    op.create_index(op.f('ix_specimen_staff_member_id'), 'specimen', ['staff_member_id'], unique=False)
    op.create_index(op.f('ix_specimen_storage_method_id'), 'specimen', ['storage_method_id'], unique=False)
    op.create_index(op.f('ix_specimen_strain_id'), 'specimen', ['strain_id'], unique=False)
    op.create_index(op.f('ix_specimen_type'), 'specimen', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_specimen_type'), table_name='specimen')
    op.drop_index(op.f('ix_specimen_strain_id'), table_name='specimen')
    op.drop_index(op.f('ix_specimen_storage_method_id'), table_name='specimen')
    op.drop_index(op.f('ix_specimen_staff_member_id'), table_name='specimen')
    op.drop_index(op.f('ix_specimen_species_id'), table_name='specimen')
    op.drop_index(op.f('ix_specimen_sample_date'), table_name='specimen')
    op.drop_index(op.f('ix_specimen_resistance_marker_id'), table_name='specimen')
    op.drop_index(op.f('ix_specimen_project_id'), table_name='specimen')
    op.drop_index(op.f('ix_specimen_position'), table_name='specimen')
    op.drop_index(op.f('ix_specimen_plasmid_id'), table_name='specimen')
    op.drop_index(op.f('ix_specimen_phage_identifier_id'), table_name='specimen')
    op.drop_index(op.f('ix_specimen_notes'), table_name='specimen')
    op.drop_index(op.f('ix_specimen_name'), table_name='specimen')
    op.drop_index(op.f('ix_specimen_medium_id'), table_name='specimen')
    op.drop_index(op.f('ix_specimen_host_id'), table_name='specimen')
    op.drop_index(op.f('ix_specimen_freezer'), table_name='specimen')
    op.drop_index(op.f('ix_specimen_drawer'), table_name='specimen')
    op.drop_index(op.f('ix_specimen_description'), table_name='specimen')
    op.drop_index(op.f('ix_specimen_box_number_id'), table_name='specimen')
    op.drop_table('specimen')
    op.drop_table('roles_users')
    op.drop_table('user')
    op.drop_table('upload')
    op.drop_index(op.f('ix_strain_name'), table_name='strain')
    op.drop_table('strain')
    op.drop_index(op.f('ix_storage_method_name'), table_name='storage_method')
    op.drop_table('storage_method')
    op.drop_index(op.f('ix_staff_member_name'), table_name='staff_member')
    op.drop_table('staff_member')
    op.drop_table('role')
    op.drop_index(op.f('ix_resistance_marker_name'), table_name='resistance_marker')
    op.drop_table('resistance_marker')
    op.drop_index(op.f('ix_project_name'), table_name='project')
    op.drop_table('project')
    op.drop_index(op.f('ix_plasmid_name'), table_name='plasmid')
    op.drop_table('plasmid')
    op.drop_index(op.f('ix_phage_identifier_name'), table_name='phage_identifier')
    op.drop_table('phage_identifier')
    op.drop_index(op.f('ix_medium_name'), table_name='medium')
    op.drop_table('medium')
    op.drop_index(op.f('ix_box_number_name'), table_name='box_number')
    op.drop_table('box_number')
    op.drop_index(op.f('ix_bacterial_species_name'), table_name='bacterial_species')
    op.drop_table('bacterial_species')
    # ### end Alembic commands ###
